language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: CjCPyQ4smt5spoId1yjtyyy9PWvh+dOqNDQwo3r96l/HJyi2ANq48E13ytNYCyTg0KVnDsHzNy0UtUCRx6Ncq4/YQcQBp6QKdc2X4BifMFs38DzFkKw7jRmbk4+maYL9lb1mKJfaUANyuAbkl3vhwM1qrkRNa8y0iTSRObDG+9TZT8S0ObXEHvpMtF5YOVp3xmzjhvnhnRdQ/US++n48Xnyp0Ipjz8NAZPO9okjLMFTYBBRxaaOUYrRjRmee3S+/1768wJsH44to3HuMc03xQM+f74eTX08awhlUiFUy5UQK69c0b4D9Q8z35r/MJ073d5fyVl6Bf0X9h37bHFo5RXHYc2jjg0lP5Yt7GhNaWss51LTLfzCYCGkTfm8yDycYO6HmeAepRS01HaD7JmpWhnipLKjzO7CYEz7i91abYmB88PIJ0oA6B7gF9rCWQMY99Faus1Ed9eld93gdlxwv54M+UTmI8mr/jGSZJopq6J5CQTo7OoPkYMWZKLufdSL3nHz0QYKRF3Q5bKPwziTOYb9R/uJzFoDtvZ9ViDmbbBUaNbHw4xSQy8sBcx2p2fVpFnKZ2Jskjrg2IVEyIhJyU4r/uPvpN2/SFnnSIqLrLnk1xmZxqNIfiPpBCFqfOqktlO0ACPgAhy9BaqZuWc0uxjJicX68vx5QjdTJWo8bZUM=
  app: josh-noteful-app-v3
  on:
    repo: thinkful-ei19/joshua-noteful-app-v3
